class AppUrls {
  AppUrls._();
  static const baseUrl = "https://starinternational.com.au/roster/api/";
  static const staffAvailability = "staffAvailability";
  static const staff_notifications_list = "staff_notifications_list";
  static const staffShiftCount = "staffShiftCount";
  static const login = "login";
  static const signup = "registration";
  static const forgetPass = "forgot_password";
  static const editProfile = "edit_profile";
  static const deleteProfile = "delete_user";
  static const getProfile = "get_profile";
  static const staffDashboard = "staffDashboard";
  static const staff_offload_shift_grab = "staff_offload_shift_grab";
  static const staff_my_calender = "staff_my_calender";
  static const staff_star_roster = "staff_star_roster";
  static const staff_grab_list = "staff_grab_list";
  static const entireMonthUnavailable = "entireMonthUnavailable";
  static const setstaffAvailability = "setstaffAvailability";
  static const setstaffAvailabilityOtherData = "setstaffAvailabilityOtherData";
  static const staff_recall_offload_shift = "retract_offload";
  static const cancel_offload = "cancel_offload";
  static const staff_offload_shift = "staff_offload_shift";
  static const save_notice_reply = "save_notice_reply";
  static const notice_board_reminder = "notice_board_reminder";
  static const getManufacturerList = "getManufacturerList";
  static const getProcedureList = "getProcedureList";
  static const getbuyALaser = "buyALaser";
  static const update_device_token = "update_device_token";
  static const get_notice_board = "get_notice_board";
  static const get_user_list="get_user_list";
  static const readvertise_offload="readvertise_offload";
}
